### ISSUE TITLE
P84～P84のコードに足りない部分があるからこれから作る人は気を付けて！！

### ISSUE THREAD

**Issue by aiueo99** [sr2mg/aituber_python_programing_example#5]
以下のコードが足りない部分を自分補完した物です！
なんで、この部分はソースコード貼ってなかったんだよー泣。（修正部分あるなら尚更掲載するべきやろ怒。☆１確定演出）しかもこれ書き込むのくそめんどっちいから、みんなのために全体のコードを乗っけてておいたよー！21歳拳才の冴えない金髪ツインテール男より(^^♪
import requests
import json

url='http://127.0.0.1:50021/'
text='こんにちは'
speaker_id=8
item_data={
  'text':text,
  'speaker':speaker_id
}
res=requests.post(url+'audio_query',params=item_data)
res_json=res.json()
print(res_json)
query_data=res_json
a_params={
  "speaker":speaker_id
}
res=requests.post(url+'synthesis',params=a_params,data=json.dumps(query_data))
print(res.conten

**Comment by sr2mg** [comment]
報告ありがとうございます！増刷分で修正させていただいています。
脱字申し訳ないです。
